config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :customers do
    collection { post :import }
  end
  root to: 'customers#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  require 'cpf_cnpj'

  validates :name, :cpf, :birthdate, presence: true
  validate :valid_cpf

  def valid_cpf
    errors.add(:cpf, 'cpf is invalid') unless CPF.valid?(cpf)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
# frozen_string_literal: true

class CustomersController < ApplicationController
  before_action :set_customer, only: %i[show edit update destroy]

  def index
    @customers = Customer.all
  end

  def show; end

  def new
    @customer = Customer.new
  end

  def edit; end

  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    response = CustomerServices::ImportFile.new.import_csv(params[:file])
    return redirect_to root_url, notice: 'Fail to import csv' unless response

    render template: 'customers/fail_import', locals: { customers: response }
  end

  private

  def set_customer
    @customer = Customer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def customer_params
    params.require(:customer).permit(:name, :cpf, :birthdate)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/customers_helper.rb
# frozen_string_literal: true

module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :cpf %>
    <%= form.text_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :birthdate %>
    <%= form.datetime_select :birthdate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/fail_import.html.erb
<p id="notice"><%= notice %></p>
<%= flash[:notice] %> 

<h1>Customers failed in import</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cpf</th>
      <th>Birthdate</th>
      <th>Errors</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.cpf %></td>
        <td><%= customer.birthdate %></td>
        <td><%= customer.errors.messages %></td>
        <td><%= link_to 'homepage', root_path %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div> 

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>
<%= flash[:notice] %> 

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cpf</th>
      <th>Birthdate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.cpf %></td>
        <td><%= customer.birthdate %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>
<div>                                                                              
  <h4> Import Customer </h4>
  <%= form_tag(import_customers_path, multpart: true) do %>                        
    <%= file_field_tag :file %>                                                    
    <%= submit_tag 'Import CSV'%>                                                                                                                                        
  <% end %>                                                                        
</div> 

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>
<%= flash[:notice] %> 

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @customer.cpf %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @customer.birthdate %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>